"""
Django settings for eidProject project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
import pymysql

# 配置PyMySQL
pymysql.install_as_MySQLdb()

# 加载环境变量
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def env_bool(name: str, default: bool = False) -> bool:
    value = os.getenv(name)
    if value is None:
        return default
    return value.lower() in ('1', 'true', 'yes', 'on')


def env_list(name: str, default: str = '') -> list[str]:
    value = os.getenv(name, default)
    return [item.strip() for item in value.split(',') if item.strip()]


def get_required_env(name: str) -> str:
    value = os.getenv(name)
    if not value:
        raise RuntimeError(f'Missing required environment variable: {name}')
    return value


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = get_required_env('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DJANGO_DEBUG', False)

ALLOWED_HOSTS = env_list('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'oauth2_provider',
    'members',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'oauth2_provider.middleware.OAuth2TokenMiddleware',
]

ROOT_URLCONF = 'eidProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'eidProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# 开发期可用 DB_ENGINE=sqlite 快速起项目，无需安装 MySQL
_db_engine = os.getenv('DB_ENGINE', 'mysql')
if _db_engine == 'sqlite':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.getenv('DB_NAME', str(BASE_DIR / 'db.sqlite3')),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': get_required_env('DB_NAME'),
            'USER': get_required_env('DB_USER'),
            'PASSWORD': get_required_env('DB_PASSWORD'),
            'HOST': get_required_env('DB_HOST'),
            'PORT': os.getenv('DB_PORT', '3306'),
            'OPTIONS': {
                'charset': 'utf8mb4',
                'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            }
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# 添加额外的静态文件目录
STATICFILES_DIRS = []
LOCAL_STATIC_DIR = BASE_DIR / 'static'
if LOCAL_STATIC_DIR.exists():
    STATICFILES_DIRS.append(LOCAL_STATIC_DIR)

# WhiteNoise 配置
WHITENOISE_MIDDLEWARE = {
    'max_age': 31536000,  # 1 year in seconds
    'allow_all_origins': True,
}

# 静态文件存储
if DEBUG:
    STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'
else:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# 添加正确的 MIME 类型配置
WHITENOISE_MIMETYPES = {
    '.js': 'application/javascript',
    '.css': 'text/css',
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# OIDC（OpenID Connect）配置 —— 采用 2026-08-27 起的新接入方案：
# Authorization Code Flow + S256 PKCE + RS256 ID Token。
# 端点默认值来自 OIDC Discovery 文档，可通过环境变量覆盖。
OIDC_ISSUER = os.getenv('OIDC_ISSUER', 'https://accountapi.emoera.com/api')
OIDC_AUTHORIZATION_ENDPOINT = os.getenv(
    'OIDC_AUTHORIZATION_ENDPOINT',
    'https://account.emoera.com/api/oauth2/authorize',
)
OIDC_TOKEN_ENDPOINT = os.getenv(
    'OIDC_TOKEN_ENDPOINT',
    'https://accountapi.emoera.com/api/oidc/token',
)
OIDC_USERINFO_ENDPOINT = os.getenv(
    'OIDC_USERINFO_ENDPOINT',
    'https://accountapi.emoera.com/api/oidc/userinfo',
)
OIDC_JWKS_URI = os.getenv(
    'OIDC_JWKS_URI',
    'https://accountapi.emoera.com/api/oidc/jwks',
)
# 复用原有环境变量名（OAUTH2_CLIENT_ID / OAUTH2_CLIENT_SECRET），
# 避免破坏现有 .env 部署。
OIDC_CLIENT_ID = get_required_env('OAUTH2_CLIENT_ID')
OIDC_CLIENT_SECRET = get_required_env('OAUTH2_CLIENT_SECRET')
OIDC_SCOPES = os.getenv('OIDC_SCOPES', 'openid profile email')
OIDC_ID_TOKEN_ALG = os.getenv('OIDC_ID_TOKEN_ALG', 'RS256')

# 修改认证后端配置
AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',  # 只使用 Django 默认的认证后端
)

# 添加登录 URL 配置
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/profile/'

# 修改 OAuth 回调设置
OAUTH_CALLBACK_URL = get_required_env('OAUTH_CALLBACK_URL')
OFFER_CONFIRM_BASE_URL = os.getenv('OFFER_CONFIRM_BASE_URL', '').rstrip('/')

# 外部认证系统（trust）与邮件模板图片配置
TRUST_API_URL = os.getenv('TRUST_API_URL', 'https://trust.emoera.com')
TRUST_SCHEME_ID = int(os.getenv('TRUST_SCHEME_ID', '3'))
INTERVIEW_EMAIL_IMAGE_URL = os.getenv(
    'INTERVIEW_EMAIL_IMAGE_URL',
    'https://eaccount.emoera.com/photos/bishitongzhi.png',
)
OFFER_EMAIL_IMAGE_URL = os.getenv(
    'OFFER_EMAIL_IMAGE_URL',
    'https://eaccount.emoera.com/photos/welcome.png',
)

# 添加 CSRF 配置
CSRF_COOKIE_SECURE = env_bool('CSRF_COOKIE_SECURE', not DEBUG)
CSRF_COOKIE_HTTPONLY = env_bool('CSRF_COOKIE_HTTPONLY', False)
CSRF_USE_SESSIONS = env_bool('CSRF_USE_SESSIONS', True)
CSRF_TRUSTED_ORIGINS = env_list('CSRF_TRUSTED_ORIGINS')

# Email settings
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', '')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_USE_SSL = env_bool('EMAIL_USE_SSL', False)
EMAIL_USE_TLS = env_bool('EMAIL_USE_TLS', True)
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)
SERVER_EMAIL = os.getenv('SERVER_EMAIL', DEFAULT_FROM_EMAIL)

# 邮件发送超时设置
EMAIL_TIMEOUT = int(os.getenv('EMAIL_TIMEOUT', '60'))

# Group robot webhooks (optional). Leave empty to disable.
# Never commit real webhook URLs or keys.
WECOM_WEBHOOK_URL = os.getenv('WECOM_WEBHOOK_URL', '')
FEISHU_WEBHOOK_URL = os.getenv('FEISHU_WEBHOOK_URL', '')
NOTIFY_WEBHOOK_URLS = os.getenv('NOTIFY_WEBHOOK_URLS', '')
