# Generated by Django 5.1.4 on 2024-12-26 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_oauth_id_alter_member_avatar_alter_member_bio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_name', models.CharField(max_length=50, verbose_name='姓名')),
                ('student_id', models.CharField(max_length=20, verbose_name='学号')),
                ('identity_type', models.CharField(choices=[('outstanding', '卓越贡献'), ('core', '核心成员'), ('active', '活跃成员'), ('management', '管理层'), ('key', '核心贡献')], max_length=20, verbose_name='身份类型')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝')], default='pending', max_length=10, verbose_name='审核状态')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
            ],
            options={
                'verbose_name': '认证申请',
                'verbose_name_plural': '认证申请',
            },
        ),
    ]
