# Generated by Django 5.1.4 on 2024-12-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_verificationapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationapplication',
            name='identity_title',
            field=models.CharField(default=0, max_length=100, verbose_name='认证身份'),
            preserve_default=False,
        ),
    ]
