# Generated by Django 5.1.4 on 2024-12-26 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_verificationapplication_identity_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='verificationapplication',
            options={'permissions': [('can_review_applications', 'Can review verification applications')], 'verbose_name': '认证申请', 'verbose_name_plural': '认证申请'},
        ),
    ]
