# Generated by Django 5.1.4 on 2024-12-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_verificationapplication_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='identity_level',
            field=models.IntegerField(choices=[(0, '未认证'), (1, '活跃成员'), (2, '核心成员'), (3, '核心贡献'), (4, '管理层'), (5, '卓越贡献')], default=0),
        ),
        migrations.AddField(
            model_name='member',
            name='identity_title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
