# Generated by Django 5.1.4 on 2025-08-03 05:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_member_identity_level_member_identity_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_name', models.CharField(max_length=50, verbose_name='真实姓名')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('interview_sent', '面试通知已发送'), ('offer_sent', '录取通知已发送'), ('offer_confirmed', 'Offer已确认'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='申请状态')),
                ('external_verification_status', models.CharField(blank=True, max_length=50, verbose_name='外部认证状态')),
                ('external_verified', models.BooleanField(default=False, verbose_name='外部认证通过')),
                ('offer_uuid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Offer确认码')),
                ('offer_confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Offer确认时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('interview_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='面试通知发送时间')),
                ('offer_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='录取通知发送时间')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member', verbose_name='成员')),
            ],
            options={
                'verbose_name': '社团报名申请',
                'verbose_name_plural': '社团报名申请',
                'permissions': [('can_review_club_applications', 'Can review club applications'), ('can_send_interview_notifications', 'Can send interview notifications'), ('can_send_offer_notifications', 'Can send offer notifications')],
            },
        ),
    ]
