# Generated by Django 5.1.15 on 2026-09-12 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_clubapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubapplication',
            name='interview_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='笔试通知发送时间'),
        ),
        migrations.AlterField(
            model_name='clubapplication',
            name='status',
            field=models.CharField(choices=[('pending', '待审核'), ('interview_sent', '笔试通知已发送'), ('offer_sent', '录取通知已发送'), ('offer_confirmed', 'Offer已确认'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='申请状态'),
        ),
        migrations.AlterField(
            model_name='member',
            name='identity_level',
            field=models.IntegerField(choices=[(0, '未认证'), (1, '活跃成员'), (2, '核心成员'), (3, '核心贡献'), (4, '管理层'), (5, '卓越贡献'), (6, '智能车团队')], default=0),
        ),
        migrations.AlterField(
            model_name='member',
            name='oauth_id',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='verificationapplication',
            name='identity_type',
            field=models.CharField(choices=[('outstanding', '卓越贡献'), ('core', '核心成员'), ('active', '活跃成员'), ('management', '管理层'), ('key', '核心贡献'), ('smart_car', '智能车团队')], max_length=20, verbose_name='身份类型'),
        ),
    ]
