# Generated by Django 5.1.4 on 2026-10-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_clubapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubapplication',
            name='rejection_reason',
            field=models.TextField(blank=True, default='', verbose_name='拒绝原因'),
        ),
        migrations.AddField(
            model_name='verificationapplication',
            name='rejection_reason',
            field=models.TextField(blank=True, default='', verbose_name='拒绝原因'),
        ),
    ]
